# Generated by Django 5.1.1 on 2024-09-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='demande',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='annulation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demande',
            name='annulation_a',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demande',
            name='annulation_a1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demande',
            name='annulation_a2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demande',
            name='annulation_b',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demande',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='engine_capacity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='first_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='informations_complementaires',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='moto_option',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='permis_a',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='permis_a1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='permis_a2',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='permis_b',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='project_purchase',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demande',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='selected_option',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='demande',
            name='vehicle_brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='demande',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='demande',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='demande',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
